MODIFY_STUDENT: "Modification des infos de cet agent",
ADD_STUDENT: "Ajout s'un nouveau membre de l'administration",
LIST_STUDENT: "Liste des menbres de l'administration",
DELETE_STUDENT: "Suppression d'un membre de l'administration",
SHOW_STUDENT: "Détails sur un membre de l'administration",
UPDATE_STUDENT: "Mise a jour d'un membre de l'administration",
STUDENT_INFO: "Information sur l'agent",