const strings = {
  APPLICATION_NAME: "Campus flow",

  ACTORS: {
    CLIENTS: "Clients",
    TECHNICIAN: "Technicians",
  },
  ROLES: {
    SUPERADMIN: "SuperAdmin",
    ADMIN: "Admin",
    TECHNICIAN: "Technician",
  },
  ERRORS: {
    BAD_CREDENTIALS: "Vos informations d'identification semblent incorrectes.",
    NETWORK: "Erreur réseau, vérifiez votre connexion Internet et réessayez",
    UNFORESEEN:
      "Oops! Une erreur inattendue est apparue. Si cela persiste, contactez le support informatique",
  },
  MESSAGES: {
    WELCOME_BACK: "Content de vous revoir",
    PLEASE_SING_IN: "Veuillez saisir vos identifiants pour vous connecter !",
    SUCCESS_SAVE: "Enregistrement effectuer avec succès",
    SUCCESS_DELETE: "Suppression effectuer avec succès",
    SUCCESS_ACTION: "Opération effectuer avec succès",
    FAILED_SAVE:
      "L'enregistrement a échoué, contactez le support si cela persiste",
    FAILED_DELETE:
      "La suppression a échoué, contactez le support si cela persiste",
    FAILED_ACTION:
      "L'Opération a échoué, contactez le support si cela persiste",
    SURE_TO_DELETE: "Etes-vous sûr que vous voulez supprimer ",
    AUTO_DISCONNECTION:
      "Votre session a expiré. Vous devez vous reconnecter. Mesure de sécurité.",
  },
  BUTTONS: {
    SING_IN: "Me connecter",
    SINGING_IN: "Connexion ...",
    SING_OUT: "Me déconnecter",
    SINGING_OUT: "Déconnexion ...",
    SAVING: "Enregistrement ...",
    SAVE: "Enregistrer",
    RESET_FORM: "Réinitialiser le formulaire",
    CANCEL: "Annuler",
    CLOSE: "Fermer",
    DELETE: "Oui",
    DELETEING: "Suppression ...",
    CONFIRM: "Oui",
    CONFIRMIMG: "En cours ...",
  },

  PERMISSIONS: {
    CAN_CREATE_CLIENT: "Client.create", //client
    CAN_READ_CLIENT: "Clients.Read",
    CAN_UPDATE_CLIENT: "Clients.Update",
    CAN_SHOW_CLIENT: "Clients.GetByID",
    CAN_DELETE_CLIENT: "Clients.Delete",
    CAN_CREATE_USER: "User.create", // user
    CAN_READ_USER: "User.Read",
    CAN_UPDATE_USER: "User.Update",
    CAN_SHOW_USER: "User.GetByID",
    CAN_DELETE_USER: "User.Delete",
    CAN_CREATE_COMPANY: "Company.create", // company
    CAN_READ_COMPANY: "Company.Read",
    CAN_UPDATE_COMPANY: "Company.Update",
    CAN_SHOW_COMPANY: "Company.GetByID",
    CAN_DELETE_COMPANY: "Company.Delete",
    CAN_CREATE_ROLE: "RolesManager.CreateRoles", // role
    CAN_READ_ROLE: "RolesManager.Read",
    CAN_UPDATE_ROLE: "RolesManager.UpdateRoles",
    CAN_SHOW_ROLE: "RolesManager.GetByID",
    CAN_DELETE_ROLE: "RolesManager.DeleteRoles",
    CAN_CREATE_CUSTONER: "Client.create", // customer
    CAN_READ_CUSTOMER: "Clients.Read",
    CAN_UPDATE_CUSTOMER: "Clients.Update",
    CAN_SHOW_CUSTOMER: "Clients.GetByID",
    CAN_DELETE_CUSTOMER: "Clients.Delete",
    CAN_CREATE_CATEGORY: "Category.create", // category
    CAN_READ_CATEGORY: "Category.Read",
    CAN_UPDATE_CATEGORY: "Category.Update",
    CAN_SHOW_CATEGORY: "Category.GetByID",
    CAN_DELETE_CATEGORY: "Category.Delete",
    CAN_CREATE_ARTICLE: "Article.create", // article
    CAN_READ_ARTICLE: "Article.Read",
    CAN_UPDATE_ARTICLE: "Article.Update",
    CAN_SHOW_ARTICLE: "Article.GetByID",
    CAN_DELETE_ARTICLE: "Article.Delete",
    CAN_CREATE_COMPETENCE: "Competence.create", // Competence
    CAN_READ_COMPETENCE: "Competence.Read",
    CAN_UPDATE_COMPETENCE: "Competence.Update",
    CAN_SHOW_COMPETENCE: "Competence.GetByID",
    CAN_DELETE_COMPETENCE: "Competence.Delete",
    CAN_CREATE_PROJECT: "Project.create", // Project
    CAN_READ_PROJECT: "Project.Read",
    CAN_UPDATE_PROJECT: "Project.Update",
    CAN_SHOW_PROJECT: "Project.GetByID",
    CAN_DELETE_PROJECT: "Project.Delete",
    CAN_CREATE_DISPATCH: "Dispatch.create", // Dispatch
    CAN_READ_DISPATCH: "Dispatch.Read",
    CAN_UPDATE_DISPATCH: "Dispatch.Update",
    CAN_SHOW_DISPATCH: "Dispatch.GetByID",
    CAN_DELETE_DISPATCH: "Dispatch.Delete",
    CAN_CREATE_QUOTE: "Quote.create", // quote
    CAN_READ_QUOTE: "Quote.Read",
    CAN_UPDATE_QUOTE: "Quote.Update",
    CAN_SHOW_QUOTE: "Quote.GetByID",
    CAN_DELETE_QUOTE: "Quote.Delete",
    CAN_CREATE_INVOICE: "Invoice.create", // invoice
    CAN_READ_INVOICE: "Invoice.Read",
    CAN_UPDATE_INVOICE: "Invoice.Update",
    CAN_SHOW_INVOICE: "Invoice.GetByID",
    CAN_DELETE_INVOICE: "Invoice.Delete",
    CAN_CREATE_PROJECT_ARTICLE: "ProjectArticle.create", // projectArticle
    CAN_READ_PROJECT_ARTICLE: "ProjectArticle.Read",
    CAN_UPDATE_PROJECT_ARTICLE: "ProjectArticle.Update",
    CAN_SHOW_PROJECT_ARTICLE: "ProjectArticle.GetByID",
    CAN_DELETE_PROJECT_ARTICLE: "ProjectArticle.Delete",
  },
  PAGES: {
    HOME: "Home",
    USER: "Users",
    CLIENT: "Client",
    CATEGORY: "Categories",
    ARTICLE: "Aritcles",
    COMPANY: "Companies",
    CUSTOMER: "Customers",
    PROJECT: "Projects",
    PROJECTARTICLE: "ProjectArticles",
    QUOTE: "Quotes",
    DISPATCH: "Dispatchs",
    COMPETENCE: "Skills",
    INVOICE: "Invoices",
    CLAIM: "Permissions",
    ROLE: "Roles",
  },
  ACTIONS: {
    DISCARD: "Discard",
    GOT_IT: "Got it",
    UPDATE: "Update",
    GO_BACK: "Go back",
    DELETE: "Delete",
    CREATE_USER: "Create new User",
    CREATE_INVOICE: "Create new Invoice",
    CREATE_USER_COMPETENCE: "Add skill",
    CREATE_ARTICLE: "Create new Article ",
    CREATE_CATEGORY: "Create new Category ",
    CREATE_COMPANY: "Create new Company ",
    CREATE_CUSTOMER: "Create new Customer ",
    CREATE_PROJECT: "Create new Project ",
    CREATE_PROJECTARTICLE: "Add an article ",
    CREATE_DISPATCH: "Create new Dispatch ",
    CREATE_QUOTE: "Initialize new Quote ",
    CREATE_COMPETENCE: "Create new Skill ",
    CREATE_ROLE: "Create new Role ",
    EDIT_PROJECT: "Edit Project ",
    EDIT_PROJECTARTICLE: "Edit ProjectArticle",
    UPDATE_PROJECTARTICLE: "Update",
    EDIT_DISPATCH: "Edit Dispatch ",
    EDIT_QUOTE: "Edit Quote ",
    UPDATE_COMPETENCE: "Upadate Skill",
    UPDATE_INVOICE: "Upadate Invoice",
    UPDATE_CUSTOMER: "Upadate Customer",
    UPDATE_PROJECT: "Upadate Project",
    UPDATE_QUOTE: "Upadate Quote",
    UPDATE_DISPATCH: "Upadate Dispatch",
    UPADATE_ARTICLE: "Upadate Artcile",
    UPDATE_ROLE: "Upadate Role",
    UPDATE_CATEGORY: "Upadate Category",
  },
};
export default strings;
