const strings = {
  APPLICATION_NAME: "Campus flow",

  ACTORS: {},
  ROLES: {},
  PLACEHOLDERS: {
    CLIK_TO_SELECT: "Cliquez pour selectionnner",
    SEARCH_TEACHER: "Rechercher ici...",
    SELECT_TEACHER: "Sélectionner un enseignant",
    REGISTRATION_NO: "Numéro de matricule",
    PHONE1: "Numéro de téléphone (WhatsApp) ici",
    PHONE2: "Numéro de téléphone de secours ici",
    EMAIL: "Adresse e-mail ici",
    PASSWORD: "Mot de passe ici",
    FIRST_NAME: "Prénom(s) ici",
    LAST_NAME: "Nom de famille ici",
    TITLE: "Saisir une phrase en guise de titre",
    BANNER: "Saisir une phrase en guise de bannière",
    VH_CM: "Saisir le volume horaire de CM",
    VH_TP: "Saisir le volume horaire de TP",
    VH_TD: "Saisir le volume horaire de TD",
    CREDIT: "Saisir le crédit",
    COEF: "Saisir le coefficient",
    DESCRIPTION: "Saisir la description",
    ACRONYM: "Saisir l'acronyme",
    CODE: "Saisir le code",
    SELECT_MODULE: "Sélectionner un module",
    CONTENU: "Contenu",
  },

  INSTRUCTIONS: {
    // Seances
    CHANGE_STATUS: "Vous pouvez changer le statut de l'utilisateur concernée.",
    APPROUVE_SEANCE: "Entrez votre matricule pour valider.",
    STUDENT_ALLOW:
      "Permettre la modification des droits d'ajout et de modification des séances par les délégués et sous-délégués de la classe.",
    // Sélection de module
    SELECT_MODULE: "Le module appartiendra-t-il à cette classe également ?",
    STATUS: "L'utilisateur sera-t-il actif ou inactif ?",
    UPDATED_AGENT:
      "Effectuez des modifications d'agent ici. Cliquez sur << Enregistrer >> lorsque vous avez terminé.",
    ADD_AGENT:
      "Ajouter un nouveau membre de l'administration ici. Cliquez sur Enregistrer lorsque vous avez terminé.",
    DELETE_AGENT:
      "Veuillez confirmer la suppression ce membre de l'administration en cliquant sur << Supprimer >>.",
    SHOW_AGENT:
      "Vous trouverez ici toutes les formations liées à ce membre de l'administration. Vous pouvez copier les informations dans votre presse-papiers en cliquant sur la donnée correspondante.",
    // Etudiants
    UPDATED_STUDENT:
      "Effectuez des modifications d'étudiant ici. Cliquez sur << Enregistrer >> lorsque vous avez terminé.",
    ADD_STUDENT:
      "Ajouter un nouvel étudiant ici. Cliquez sur Enregistrer lorsque vous avez terminé.",
    DELETE_STUDENT:
      "Veuillez confirmer la suppression d'un étudiant  en cliquant sur << Supprimer >>.",
    SHOW_STUDENT:
      "Vous trouverez ici toutes les formations liées à cet étudiant. Vous pouvez copier les informations dans votre presse-papiers en cliquant sur la donnée correspondante.",
    // Enseignants
    UPDATED_TEACHER:
      "Effectuez des modifications d'enseignant ici. Cliquez sur << Enregistrer >> lorsque vous avez terminé.",
    ADD_TEACHER:
      "Ajouter un nouvel enseignant ici. Cliquez sur Enregistrer lorsque vous avez terminé.",
    DELETE_TEACHER:
      "Veuillez confirmer la suppression cet enseignant en cliquant sur << Supprimer >>.",
    SHOW_TEACHER:
      "Vous trouverez ici toutes les formations liées à cet enseignant. Vous pouvez copier les informations dans votre presse-papiers en cliquant sur la donnée correspondante.",
    // Classes
    UPDATED_CLASSE:
      "Effectuez des modifications d'une classe ici. Cliquez sur Enregistrer lorsque vous avez terminé.",
    ADD_CLASSE:
      "Ajouter une nouvelle classe ici. Cliquez sur Enregistrer lorsque vous avez terminé.",
    DELETE_CLASSE:
      "Veuillez confirmer la suppression d'une classe  en cliquant sur << Supprimer >>",
    SHOW_CLASSE:
      "Vous trouverez ici toutes les formations liées à cette classe. Vous pouvez copier les informations dans votre presse-papiers en cliquant sur la donnée correspondante.",
    // Séances
    UPDATED_SEANCE:
      "Effectuez des modifications de séance ici. Cliquez sur Enregistrer lorsque vous avez terminé.",
    ADD_SEANCE:
      "Ajouter une nouvelle séance ici. Cliquez sur Enregistrer lorsque vous avez terminé.",
    DELETE_SEANCE:
      "Veuillez confirmer la suppression d'une séance en cliquant sur << Supprimer >>",
    SHOW_SEANCE:
      "Vous trouverez ici toutes les formations liées à cette séance. Vous pouvez copier les informations dans votre presse-papiers en cliquant sur la donnée correspondante.",
    // Modules
    UPDATED_MODULE:
      "Effectuez des modifications d'un module ici. Cliquez sur << Enregistrer >> lorsque vous avez terminé.",
    ADD_MODULE:
      "Ajouter un nouveau module ici. Cliquez sur << Enregistrer >> lorsque vous avez terminé.",
    DELETE_MODULE:
      "Veuillez confirmer la suppression du module  en cliquant sur << Supprimer >>.",
    SHOW_MODULE:
      "Vous trouverez ici toutes les formations liées à ce module. Vous pouvez copier les informations dans votre presse-papiers en cliquant sur la donnée correspondante.",
  },
  TOOLTIPS: {
    PARAMS_LIST: "Liste des paramètres",
    USERS_LIST: "Liste des membres de l'administration",
    ADD_AGENT: "Ajouter un nouveau membre de l'administration",
    ADD_SEANCE: "Ajouter une nouvelle séance",
    ADD_STUDENT: "Ajouter un nouvel étudiant",
    ADD_TEACHER: "Ajouter un nouveau enseignant",
    ADD_MODULE: "Ajouter un nouveau module",
    NOT_YET_AVAILABLE: "Pas encore disponible",
    CLASSE_LIST: "Aller à la liste de toutes les classes",
  },
  ERRORS: {
    INACTIVE_USER:
      "Votre compte est actuellement inactif, ou n'existe pas.Contactez un administrateur.",
    BAD_CREDENTIALS: "Vos informations d'identification semblent incorrectes.",
    NETWORK:
      "Erreur réseau. Veuillez vérifier votre connexion Internet et réessayer.",
    UNFORESEEN:
      "Oops ! Une erreur inattendue est survenue. Si le problème persiste, veuillez contacter le support informatique.",
  },
  TEXTS: {
    WELCOME: "Bienvenue",
    PROGRESSION_BY_DEP: "Progression par déartement",
    YEAR_PROGRESSION: "Progression de l'année",
    DISCONNECT: "Me déconnecter",
    HOME: "Page d'accueil",
    BON_RETOUR: "Bon retour parmi nous !",
    LOGIN_FORM: "Formulaire de connexion",
    BAD_REGISTRATION_NUMBER_MESSAGE:
      "Le numéro matricule que vous avez entré est incorrect ou ne vous appartient pas.",
    BAD_REGISTRATION_NUMBER_TITLE:
      "Oups, il y a une erreur sur votre matricule",
    MODULE_DIPENSED_BY: "Module dispensé par :",
    MY_ACCOUNT: "Mon compte",
    LIST_PERMISSIONS: "Liste des permissions",
    MODIFY_AGENT: "Modification des informations de cet agent",
    ADD_AGENT: "Ajout d'un nouveau membre de l'administration",
    LIST_AGENT: "Liste des membres de l'administration",
    DELETE_AGENT: "Suppression d'un membre de l'administration",
    SHOW_AGENT: "Détails sur un membre de l'administration",
    UPDATE_AGENT: "Mise à jour d'un membre de l'administration",
    AGENT_INFO: "Information sur l'agent",
    // Student
    MODIFY_STUDENT: "Modification des informations de cet étudiant",
    ADD_STUDENT: "Ajout d'un nouveau étudiant",
    LIST_STUDENT: "Liste des étudiants",
    DELETE_STUDENT: "Suppression d'un étudiant",
    SHOW_STUDENT: "Détails sur un étudiant",
    UPDATE_STUDENT: "Mise à jour d'un étudiant",
    STUDENT_INFO: "Information sur l'étudiant",
    RESPONSIBILITY: "Changer les responsabilités de l'étudiant",
    // Teacher
    MODIFY_TEACHER: "Modification des informations de cet enseignant",
    ADD_TEACHER: "Ajout d'un nouveau enseignant",
    LIST_TEACHER: "Liste des enseignants",
    DELETE_TEACHER: "Suppression d'un enseignant",
    SHOW_TEACHER: "Détails sur un enseignant",
    UPDATE_TEACHER: "Mise à jour d'un enseignant",
    TEACHER_INFO: "Information sur l'enseignant",
    // Seance
    MODIFY_SEANCE: "Modification des informations de cette séance",
    ADD_SEANCE: "Ajout d'une nouvelle séance",
    LIST_SEANCE: "Liste des séances",
    DELETE_SEANCE: "Suppression d'une séance",
    SHOW_SEANCE: "Détails sur une séance",
    UPDATE_SEANCE: "Mise à jour d'une séance",
    SEANCE_INFO: "Information sur la séance",
    STUDENT_ALLOW: "Droit d'ajout par délégué",
    STUDENT_ALLOW_NON: "Accès en écriture délégués : Non",
    STUDENT_ALLOW_YES: "Accès en écriture délégués : Oui",
    // Departements
    LIST_DEPARTEMENT: "Liste des départements",
    DEPARTEMENT_EMPTY: "Aucun département trouvé",
    PERMISSIONS_EMPTY: "Aucune permission trouvée",
    // classes
    LIST_CLASSE_OF_DEPARTEMENT: "Liste des classes du département",
    MODIFY_CLASSE: "Modification des informations de cette classe",
    ADD_CLASSE: "Ajout d'une nouvelle classe",
    LIST_CLASSE: "Liste des classes",
    DELETE_CLASSE: "Suppression d'une classe",
    SHOW_CLASSE: "Détails de cette classe",
    UPDATE_CLASSE: "Mise à jour d'une classe",
    CLASSE_INFO: "Information sur la classe",
    CLASSE_EMPTY: "Aucune classe",
    // Module
    MODIFY_MODULE: "Modification des informations de ce module",
    ADD_MODULE: "Ajout d'un nouveau module",
    LIST_MODULE: "Liste des modules",
    DELETE_MODULE: "Suppression d'un module",
    SHOW_MODULE: "Détails sur un module",
    UPDATE_MODULE: "Mise à jour d'un module",
    MODULE_INFO: "Information sur le module",
    VH: "Volumes horaires",
    HEURES: "heures",
    NOT_YET_ASSIGNED: "Le module n'est pas encore assigné.",
    ASSIGNE_TO_PROF: "Assignation de module",
    MY_MODULES_LIST: "Liste de mes modules",
    /// DCNFSUM
    ADD_DCNFSUM: "Ajouter un module à cette classe",
    // Spécifique
    PERSONNE_INFO: "Information sur la personne",
    GENERAL_INFO: "Informations générales",
    PLUS: "Plus",
    VALIDATIONS: "Validations",
    USERS: "Utilisateurs",
    SETTINGS: "Paramètres du système",
    // Seances
    NO_SEANCES: "Aucune séance pour le moment",
    APPROUVE_SEANCE: "Viser la séance",
    // visa
    VISA_STUDENT: "Visa Délégué",
    VISA_AGENT: "Visa Administration",
    VISA_TEACHER: "Visa Enseignant",
    // my classes
    MY_CLASSES_LIST: "Liste de mes classes",
    CHANGE_STATUS: "Changer le statut",
    // Role et permissions
    ROLE_LIST: "Liste des rôles",
  },
  TH: {
    PASSWORD: "Mot de passe",
    DOSSIER_AGENT: "Mon dossier membre de l'adminitration",
    DOSSIER_TEACHER: "Mon dossier enseignant",
    DOSSIER_STUDENT: "Mon dossier étudiant",
    PERSONAL_INFO: "Informations personnelles",
    MY_EDT: "Mon emploi du temps",
    EXAMS: "Evaluations",
    NONE: "Aucun",
    RESPONSIBILITY: "Responsabilité",
    DELEGUE: "Délégué",
    SUB_DELEGUE: "Délégué Adjoint",
    DELEGUE_INTER: "Délégué Intérimaire",
    SUB_DELEGUE_INTER: "Délégué Adjoint Intérimaire",
    ROLE_PERMISSIONS: "Rôles et permissions",
    EDT: "Emploi du temps",
    MODULES: "Modules",
    MY_YEAR: "Mon année",
    SEANCES: "Séances",
    MY_DOCS: "Mes documents",
    MY_STATS: "Mes statistiques",
    MY_MODULES: "Mes modules",
    MY_CLASSES: "Mes classes",
    MY_COURSES: "Mes cours",
    DEPARTEMENT: "Départements",
    PARAMS: "Paramètres",
    AGENT: "Agents",
    TEACHER: "Enseignants",
    STUDENT: "Étudiants",
    PROGRESS: "Progression",
    CONTENT: "Contenu",
    CREATED_AT: "Date de création",
    VHT: "VHT",
    MODULE: "Module",
    DESCRIPTION: "Description",
    COEF: "Coefficient",
    CREDIT: "Crédit",
    STUDENT_COUNT: "Nombre d'étudiants",
    FILIERE: "Filière",
    VH_CM: "CM",
    VH_TD: "TD",
    VH_TP: "TP",
    CODE: "Code",
    NIVEAU: "Niveau",
    CLASSE: "Classe",
    ACRONYM: "Acronyme",
    PHONE1: "Téléphone 1 (WhatsApp)",
    PHONE2: "Téléphone 2",
    EMAIL: "Adresse e-mail",
    FIRST_NAME: "Prénom(s)",
    LAST_NAME: "Nom",
    REGISTRATION_NO: "Numéro de matricule",
    TITLE: "Titre",
    BANNER: "Bannière",
    GENDER: "Genre",
    STATUS: "Statut",
    MASCULIN: "Masculin",
    FEMININ: "Féminin",
    CLASSES: "Classes",
    STATISTICS: "Statistiques",
    STUDENTS: "Étudiants",
  },
  MESSAGES: {
    NO_DATA: "Humm, nous n'avons rien trouvé",
    WELCOME_BACK: "Content de vous revoir",
    PLEASE_SIGN_IN: "Veuillez saisir vos identifiants pour vous connecter !",
    SUCCESS_SAVE: "Enregistrement effectué avec succès",
    SUCCESS_DELETE: "Suppression effectuée avec succès",
    SUCCESS_ACTION: "Opération effectuée avec succès",
    FAILED_SAVE:
      "L'enregistrement a échoué, contactez le support si cela persiste",
    FAILED_DELETE:
      "La suppression a échoué, contactez le support si cela persiste",
    FAILED_ACTION:
      "L'opération a échoué, contactez le support si cela persiste",
    SURE_TO_DELETE: "Êtes-vous sûr de vouloir supprimer ",
    AUTO_DISCONNECTION:
      "Votre session a expiré. Vous devez vous reconnecter pour des raisons de sécurité.",
  },
  BUTTONS: {
    RESPONSABILITE: "Responsabilité",
    STATUS: "Statut",
    YES_CHANGE: "Oui, changer",
    ASSIGNE_TO_PROF: "Assigner au professeur",
    WITHDRAW: "Retirer",
    SING_IN: "Me connecter",
    SINGING_IN: "Connexion en cours...",
    SING_OUT: "Me déconnecter",
    SINGING_OUT: "Déconnexion en cours...",
    SAVING: "Enregistrement en cours...",
    SAVE: "Enregistrer",
    RESET_FORM: "Réinitialiser le formulaire",
    CANCEL: "Annuler",
    CLOSE: "Fermer",
    DELETE: "Supprimer",
    DELETING: "Suppression en cours...",
    CONFIRM: "Confirmer",
    CONFIRMING: "Confirmation en cours...",
    ADD: "Ajouter",
    EDIT: "Modifier",
    SHOW: "Afficher",
    OK_CLOSE: "OK, fermer",
    UPDATING: "Mise à jour en cours...",
    UPDATE: "Mettre à jour",
  },

  PERMISSIONS: {
    // myInformations
    MY_STUDENT_INFORMATION: "myInformations.student",
    MY_TEACHER_INFORMATION: "myInformations.teacher",
    MY_AGENT_INFORMATION: "myInformations.agent",
    MY_USER_INFORMATION: "myInformations.user",
    //delegue
    DELEGUE: "delegue",
    SUB_DELEGUE: "sub_delegue",
    DELEGUE_INTER: "delegue_inter",
    SUB_DELEGUE_INTER: "sub_delegue_inter",
    // Stats
    STATS: "stats",
    // User
    USER_ACTIVE: "users.active",
    //Params
    PARAMS_LIST: "params.list",
    PARAMS_CLASSES: "params.classes",
    PARAMS_DEPARTEMENTS: "params.departements",
    PARAMS_USERS: "params.users",
    // my
    MY_COURSES: "my.courses",
    MY_YEAR: "my.year",
    // Agent
    AGENT_LIST: "agents.list",
    AGENT_SHOW: "agents.show",
    AGENT_UPDATE: "agents.update",
    AGENT_STORE: "agents.store",
    AGENT_DESTROY: "agents.destroy",
    AGENT_RESTORE: "agents.restore",
    AGENT_TRASHED: "agents.trashed",
    AGENT_DESTROY_TRASHED: "agents.destroyTrashed",
    AGENT_SHOW_TRASHED: "agents.showTrashed",
    // Agentuser
    AGENT_USER_LIST: "agentUser.list",
    AGENT_USER_SHOW: "agentUser.show",
    AGENT_USER_UPDATE: "agentUser.update",
    AGENT_USER_STORE: "agentUser.store",
    AGENT_USER_DESTROY: "agentUser.destroy",
    AGENT_USER_RESTORE: "agentUser.restore",
    AGENT_USER_TRASHED: "agentUser.trashed",
    AGENT_USER_DESTROY_TRASHED: "agentUser.destroyTrashed",
    AGENT_USER_SHOW_TRASHED: "agentUser.showTrashed",
    // TEACHER
    TEACHER_LIST: "teachers.list",
    TEACHER_SHOW: "teachers.show",
    TEACHER_UPDATE: "teachers.update",
    TEACHER_STORE: "teachers.store",
    TEACHER_DESTROY: "teachers.destroy",
    TEACHER_RESTORE: "teachers.restore",
    TEACHER_TRASHED: "teachers.trashed",
    TEACHER_DESTROY_TRASHED: "teachers.destroyTrashed",
    TEACHER_SHOW_TRASHED: "teachers.showTrashed",
    // TeacherUser
    TEACHER_USER_LIST: "teacherUser.list",
    TEACHER_USER_SHOW: "teacherUser.show",
    TEACHER_USER_UPDATE: "teacherUser.update",
    TEACHER_USER_STORE: "teacherUser.store",
    TEACHER_USER_DESTROY: "teacherUser.destroy",
    TEACHER_USER_RESTORE: "teacherUser.restore",
    TEACHER_USER_TRASHED: "teacherUser.trashed",
    TEACHER_USER_DESTROY_TRASHED: "teacherUser.destroyTrashed",
    TEACHER_USER_SHOW_TRASHED: "teacherUser.showTrashed",
    // STUDENT
    STUDENT_LIST: "students.list",
    STUDENT_SHOW: "students.show",
    STUDENT_UPDATE: "students.update",
    STUDENT_STORE: "students.store",
    STUDENT_DESTROY: "students.destroy",
    STUDENT_RESTORE: "students.restore",
    STUDENT_TRASHED: "students.trashed",
    STUDENT_DESTROY_TRASHED: "students.destroyTrashed",
    STUDENT_SHOW_TRASHED: "students.showTrashed",
    STUDENT_CHANGE_AUTORITY: "students.changeAutority",
    // StudentUser
    STUDENT_USER_LIST: "studentUser.list",
    STUDENT_USER_SHOW: "studentUser.show",
    STUDENT_USER_UPDATE: "studentUser.update",
    STUDENT_USER_STORE: "studentUser.store",
    STUDENT_USER_DESTROY: "studentUser.destroy",
    STUDENT_USER_RESTORE: "studentUser.restore",
    STUDENT_USER_TRASHED: "studentUser.trashed",
    STUDENT_USER_DESTROY_TRASHED: "studentUser.destroyTrashed",
    STUDENT_USER_SHOW_TRASHED: "studentUser.showTrashed",
    // NF
    NF_LIST: "n_f.list",
    NF_SHOW: "n_f.show",
    NF_UPDATE: "n_f.update",
    NF_STORE: "n_f.store",
    NF_DESTROY: "n_f.destroy",
    NF_RESTORE: "n_f.restore",
    NF_TRASHED: "n_f.trashed",
    NF_DESTROY_TRASHED: "n_f.destroyTrashed",
    NF_SHOW_TRASHED: "n_f.showTrashed",
    // DC
    DC_LIST: "d_c.list",
    DC_SHOW: "d_c.show",
    DC_UPDATE: "d_c.update",
    DC_STORE: "d_c.store",
    DC_DESTROY: "d_c.destroy",
    DC_RESTORE: "d_c.restore",
    DC_TRASHED: "d_c.trashed",
    DC_DESTROY_TRASHED: "d_c.destroyTrashed",
    DC_SHOW_TRASHED: "d_c.showTrashed",
    // DCNF
    DCNF_LIST: "dc_nf.list",
    DCNF_SHOW: "dc_nf.show",
    DCNF_UPDATE: "dc_nf.update",
    DCNF_STORE: "dc_nf.store",
    DCNF_DESTROY: "dc_nf.destroy",
    DCNF_RESTORE: "dc_nf.restore",
    DCNF_TRASHED: "dc_nf.trashed",
    DCNF_DESTROY_TRASHED: "dc_nf.destroyTrashed",
    DCNF_SHOW_TRASHED: "dc_nf.showTrashed",
    // DCNFS
    DCNFS_LIST: "dcnf_s.list",
    DCNFS_SHOW: "dcnf_s.show",
    DCNFS_UPDATE: "dcnf_s.update",
    DCNFS_STORE: "dcnf_s.store",
    DCNFS_DESTROY: "dcnf_s.destroy",
    DCNFS_RESTORE: "dcnf_s.restore",
    DCNFS_TRASHED: "dcnf_s.trashed",
    DCNFS_DESTROY_TRASHED: "dcnf_s.destroyTrashed",
    DCNFS_SHOW_TRASHED: "dcnf_s.showTrashed",
    // MODULES
    MODULES_LIST: "modules.list",
    MODULES_SHOW: "modules.show",
    MODULES_UPDATE: "modules.update",
    MODULES_STORE: "modules.store",
    MODULES_DESTROY: "modules.destroy",
    MODULES_RESTORE: "modules.restore",
    MODULES_TRASHED: "modules.trashed",
    MODULES_DESTROY_TRASHED: "modules.destroyTrashed",
    MODULES_SHOW_TRASHED: "modules.showTrashed",
    // DCNFSUM
    DCNFSUM_LIST: "dcnf_sum.list",
    DCNFSUM_SHOW: "dcnf_sum.show",
    DCNFSUM_UPDATE: "dcnf_sum.update",
    DCNFSUM_STORE: "dcnf_sum.store",
    DCNFSUM_DESTROY: "dcnf_sum.destroy",
    DCNFSUM_RESTORE: "dcnf_sum.restore",
    DCNFSUM_TRASHED: "dcnf_sum.trashed",
    DCNFSUM_DESTROY_TRASHED: "dcnf_sum.destroyTrashed",
    DCNFSUM_SHOW_TRASHED: "dcnf_sum.showTrashed",
    // SUM
    SUM_LIST: "su_m.list",
    SUM_SHOW: "su_m.show",
    SUM_UPDATE: "su_m.update",
    SUM_STORE: "su_m.store",
    SUM_DESTROY: "su_m.destroy",
    SUM_RESTORE: "su_m.restore",
    SUM_TRASHED: "su_m.trashed",
    SUM_DESTROY_TRASHED: "su_m.destroyTrashed",
    SUM_SHOW_TRASHED: "su_m.showTrashed",
    // DCNFSUMT
    DCNFSUMT_LIST: "dcnfsum_t.list",
    DCNFSUMT_SHOW: "dcnfsum_t.show",
    DCNFSUMT_UPDATE: "dcnfsum_t.update",
    DCNFSUMT_STORE: "dcnfsum_t.store",
    DCNFSUMT_DESTROY: "dcnfsum_t.destroy",
    DCNFSUMT_RESTORE: "dcnfsum_t.restore",
    DCNFSUMT_TRASHED: "dcnfsum_t.trashed",
    DCNFSUMT_DESTROY_TRASHED: "dcnfsum_t.destroyTrashed",
    DCNFSUMT_SHOW_TRASHED: "dcnfsum_t.showTrashed",
    // ROLE
    ROLE_LIST: "roles.list",
    ROLE_SHOW: "roles.show",
    ROLE_UPDATE: "roles.update",
    ROLE_STORE: "roles.store",
    ROLE_DESTROY: "roles.destroy",
    ROLE_RESTORE: "roles.restore",
    ROLE_TRASHED: "roles.trashed",
    ROLE_DESTROY_TRASHED: "roles.destroyTrashed",
    ROLE_SHOW_TRASHED: "roles.showTrashed",
    // SEANCE
    SEANCE_LIST: "seances.list",
    SEANCE_SHOW: "seances.show",
    SEANCE_UPDATE: "seances.update",
    SEANCE_STORE: "seances.store",
    SEANCE_DESTROY: "seances.destroy",
    SEANCE_RESTORE: "seances.restore",
    SEANCE_TRASHED: "seances.trashed",
    SEANCE_DESTROY_TRASHED: "seances.destroyTrashed",
    SEANCE_SHOW_TRASHED: "seances.showTrashed",
    SEANCE_STUDENT_APPROUVES: "seances.studentApprouves",
    SEANCE_AGENT_APPROUVES: "seances.agentApprouves",
    SEANCE_TEACHER_APPROUVES: "seances.teacherApprouves",
  },
  PAGES: {},
  ACTIONS: {},
};
export default strings;
